#+title: Fish Configuration
#+PROPERTY: :header-args:fish: :noweb yes

* Preprocessor Constants
#+NAME: CONFIG_ROOT
#+begin_src fish
/home/sridaran/.config/fish
#+end_src
* Startup Code
:PROPERTIES:
:header-args:fish: :tangle ./config.fish :noweb yes
:END:
First and foremost, let's source our environment file.
#+begin_src fish
source <<CONFIG_ROOT>>/env.fish
#+end_src

** Initializing Plugins
Initialize ~opam~.
#+begin_src fish
source /home/sridaran/.opam/opam-init/init.fish > /dev/null 2> /dev/null; or true
#+end_src

Initialize ~starship~ and ~zoxide~.
#+begin_src fish
starship init fish | source
zoxide init fish | source
#+end_src
** Set Fish Greeting
#+begin_src fish
function fish_greeting
end

funcsave fish_greeting 2> /dev/null > /dev/null
#+end_src
** Set Vi Bindings
#+begin_src fish
function my_vi_bindings
  fish_vi_key_bindings
  bind -M insert -m default jk backward-char force-repaint
end

set -g fish_key_bindings my_vi_bindings
#+end_src
*** Override Mode Cursors
The default cursors made me uncomfortable, mainly the blinking line cursor in insert mode.
#+begin_src fish
set fish_cursor_visual block
set fish_cursor_normal block blink
set fish_cursor_unknown block blink
set fish_cursor_insert block
set fish_cursor_replace_one underscore
#+end_src
** Sourcing Other Config Files
Before sourcing our external files, let's first source our ~functions.fish~ script, which contains all of our core aliases and functions.
#+begin_src fish
source <<CONFIG_ROOT>>/functions.fish
#+end_src

Next, let's source our ~misc_setups.fish~ script, which contains our Literate configurations for different setups/projects.
#+begin_src fish
source <<CONFIG_ROOT>>/misc_setups.fish
#+end_src
** Sourcing External Files
Let's source all ~fish~ files under our ~custom-functions~ directory, for things that are not tracked under our Literate configuration.

#+begin_src fish
for file in <<CONFIG_ROOT>>/custom-functions/**.fish
    source "$file"
end
#+end_src
** Set Fzf Keybindings
#+begin_src fish
fzf_key_bindings
#+end_src
* Functions
:PROPERTIES:
:header-args:python: :tangle ./functions.fish
:END:
* Environment Variables
:PROPERTIES:
:header-args:python: :tangle ./env.fish
:END:
* Plugin Configuration
:PROPERTIES:
:header-args:python: :tangle ./plugin_config.fish
:END:
